
import javax.swing.ButtonGroup;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rauf Mazzidan
 */
public class Latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label7 = new java.awt.Label();
        Nama = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        Absen = new java.awt.TextField();
        rdb1 = new javax.swing.JRadioButton();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        cb3 = new javax.swing.JCheckBox();
        cb4 = new javax.swing.JCheckBox();
        Submit = new java.awt.Button();
        Hapus = new java.awt.Button();
        Exit = new java.awt.Button();
        TA = new java.awt.TextArea();
        label8 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        rdb2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label7.setBackground(new java.awt.Color(153, 255, 255));
        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText("Hasil");
        getContentPane().add(label7);
        label7.setBounds(50, 210, 40, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(140, 30, 180, 30);

        label1.setBackground(new java.awt.Color(153, 255, 255));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Nama");
        getContentPane().add(label1);
        label1.setBounds(70, 30, 37, 30);

        label2.setBackground(new java.awt.Color(153, 255, 255));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Hobi");
        getContentPane().add(label2);
        label2.setBounds(70, 130, 29, 30);

        Absen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbsenActionPerformed(evt);
            }
        });
        getContentPane().add(Absen);
        Absen.setBounds(140, 60, 180, 30);

        rdb1.setBackground(new java.awt.Color(153, 255, 255));
        rdb1.setText("RPL");
        getContentPane().add(rdb1);
        rdb1.setBounds(140, 100, 80, 23);

        cb1.setBackground(new java.awt.Color(153, 255, 255));
        cb1.setLabel("Teknisi");
        getContentPane().add(cb1);
        cb1.setBounds(240, 130, 90, 23);

        cb2.setBackground(new java.awt.Color(153, 255, 255));
        cb2.setText("Programming");
        getContentPane().add(cb2);
        cb2.setBounds(140, 130, 90, 23);

        cb3.setBackground(new java.awt.Color(153, 255, 255));
        cb3.setLabel("Designer");
        getContentPane().add(cb3);
        cb3.setBounds(240, 160, 90, 23);

        cb4.setBackground(new java.awt.Color(153, 255, 255));
        cb4.setLabel("Animasi");
        getContentPane().add(cb4);
        cb4.setBounds(140, 160, 90, 23);

        Submit.setLabel("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        getContentPane().add(Submit);
        Submit.setBounds(117, 190, 70, 30);

        Hapus.setLabel("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(210, 190, 60, 30);

        Exit.setLabel("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(290, 190, 60, 30);
        getContentPane().add(TA);
        TA.setBounds(20, 240, 350, 130);

        label8.setBackground(new java.awt.Color(153, 255, 255));
        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText("Biodata Siswa");
        getContentPane().add(label8);
        label8.setBounds(170, 0, 90, 30);

        label3.setBackground(new java.awt.Color(153, 255, 255));
        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Absen");
        getContentPane().add(label3);
        label3.setBounds(70, 60, 40, 30);

        label4.setBackground(new java.awt.Color(153, 255, 255));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Jurusan");
        getContentPane().add(label4);
        label4.setBounds(70, 100, 50, 30);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        rdb2.setBackground(new java.awt.Color(153, 255, 255));
        rdb2.setText("TKJ");
        jPanel1.add(rdb2);
        rdb2.setBounds(220, 100, 93, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 370);

        setBounds(0, 0, 416, 410);
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void AbsenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbsenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AbsenActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String jurusan;
        String hobi="";
        //Radio
            if (rdb1.isSelected()) {
            jurusan="RPL";
            }
            else if (rdb2.isSelected()){
            jurusan="TKJ";
            } else{
            jurusan = " ";
            }
        //CheckBox
            if (cb1.isSelected())
            hobi+=cb1.getText()+", ";
            if (cb2.isSelected())
            hobi+=cb2.getText()+", ";
            if (cb3.isSelected())
            hobi+=cb3.getText()+", ";
            if (cb4.isSelected())
            hobi+=cb4.getText()+", ";
           TA.setText("Nama Siswa    :"+nama+
                      "\nAbsen Siswa :"+absen+
                      "\nJurusan     :"+jurusan+
                      "\nHobi        :"+hobi);
    }//GEN-LAST:event_SubmitActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        TA.setText("");
        Nama.setText("");
        Absen.setText("");
        rdb1.setSelected(false);
        rdb2.setSelected(false);
        cb1.setSelected(false);
        cb2.setSelected(false);
        cb3.setSelected(false);
        cb4.setSelected(false);
    }//GEN-LAST:event_HapusActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Absen;
    private java.awt.Button Exit;
    private java.awt.Button Hapus;
    private java.awt.TextField Nama;
    private java.awt.Button Submit;
    private java.awt.TextArea TA;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JCheckBox cb3;
    private javax.swing.JCheckBox cb4;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
