/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rauf Mazzidan
 */
public class Latihan3 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan3
     */
    public Latihan3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        Bil2 = new java.awt.TextField();
        Bil1 = new java.awt.TextField();
        label2 = new java.awt.Label();
        Kurang = new java.awt.Button();
        Tambah = new java.awt.Button();
        Kali = new java.awt.Button();
        Bagi = new java.awt.Button();
        Hasil = new java.awt.TextField();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Kalkulator Sederhana");
        getContentPane().add(label1);
        label1.setBounds(120, 10, 160, 20);
        getContentPane().add(Bil2);
        Bil2.setBounds(190, 100, 90, 30);
        getContentPane().add(Bil1);
        Bil1.setBounds(190, 60, 90, 30);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Operator");
        getContentPane().add(label2);
        label2.setBounds(170, 140, 80, 20);

        Kurang.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kurang.setLabel("-");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });
        getContentPane().add(Kurang);
        Kurang.setBounds(150, 170, 40, 40);

        Tambah.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Tambah.setLabel("+");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });
        getContentPane().add(Tambah);
        Tambah.setBounds(100, 170, 40, 40);

        Kali.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kali.setLabel("x");
        Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliActionPerformed(evt);
            }
        });
        getContentPane().add(Kali);
        Kali.setBounds(250, 170, 40, 40);

        Bagi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Bagi.setLabel(":");
        Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiActionPerformed(evt);
            }
        });
        getContentPane().add(Bagi);
        Bagi.setBounds(200, 170, 40, 40);
        getContentPane().add(Hasil);
        Hasil.setBounds(130, 230, 150, 60);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Bilangan 2");
        getContentPane().add(label3);
        label3.setBounds(90, 100, 70, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Bilangan 1");
        getContentPane().add(label4);
        label4.setBounds(88, 60, 70, 20);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliActionPerformed
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        int hasil = bil1 * bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_KaliActionPerformed

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        int hasil = bil1 - bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_KurangActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
    int bil1 = Integer.parseInt(Bil1.getText());
        int bil2 = Integer.parseInt(Bil2.getText());
        int hasil = bil1 + bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_TambahActionPerformed

    private void BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiActionPerformed
        double bil1 = Double.parseDouble(Bil1.getText());
        double bil2 = Double.parseDouble(Bil2.getText());
        double hasil = bil1 / bil2;
        Hasil.setText(String.valueOf(hasil));
    }//GEN-LAST:event_BagiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Bagi;
    private java.awt.TextField Bil1;
    private java.awt.TextField Bil2;
    private java.awt.TextField Hasil;
    private java.awt.Button Kali;
    private java.awt.Button Kurang;
    private java.awt.Button Tambah;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
