/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rauf Mazzidan
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nilai = new java.awt.TextField();
        Nama = new java.awt.TextField();
        Absen = new java.awt.TextField();
        Mapel = new java.awt.TextField();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        Proses = new java.awt.Button();
        TA = new java.awt.TextArea();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(Nilai);
        Nilai.setBounds(160, 140, 150, 20);
        getContentPane().add(Nama);
        Nama.setBounds(160, 50, 150, 20);
        getContentPane().add(Absen);
        Absen.setBounds(160, 80, 150, 20);
        getContentPane().add(Mapel);
        Mapel.setBounds(160, 110, 150, 20);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Nilai");
        getContentPane().add(label1);
        label1.setBounds(70, 140, 39, 20);

        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText("Nama");
        getContentPane().add(label2);
        label2.setBounds(70, 50, 37, 20);

        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText("Absen");
        getContentPane().add(label3);
        label3.setBounds(70, 80, 40, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText("Matpel");
        getContentPane().add(label4);
        label4.setBounds(70, 110, 42, 20);

        Proses.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        Proses.setLabel("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(250, 170, 57, 24);
        getContentPane().add(TA);
        TA.setBounds(30, 210, 340, 140);

        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText("Penilaian Siswa");
        getContentPane().add(label5);
        label5.setBounds(150, 10, 100, 20);

        setBounds(0, 0, 416, 399);
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        String nama = Nama.getText();
        String absen = Absen.getText();
        String mapel = Mapel.getText();
        String nilai = Nilai.getText();
        
        int ket = Integer.parseInt(Nilai.getText());
        String kete;
        if(ket > 100 ){
           kete = "Amazing";
        } else if(ket == 100 ){
           kete = "Sempurna";
        } else if(ket >= 75 ){
           kete = "Lulus";
        } else{
           kete = "Tidak Lulus";
        } 
        
        TA.setText("Nama Siswa  :"+nama+"\n"+"Absen              :"+absen+"\n"+"Mapel               :"+mapel+"\n"+"Nilai                  :"+nilai+"\n"+"Keterangan     :"+kete);
    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Absen;
    private java.awt.TextField Mapel;
    private java.awt.TextField Nama;
    private java.awt.TextField Nilai;
    private java.awt.Button Proses;
    private java.awt.TextArea TA;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    // End of variables declaration//GEN-END:variables
}
