/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rauf Mazzidan
 */
public class Quiz2 extends javax.swing.JFrame {

    /**
     * Creates new form Quiz2
     */
    public Quiz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        harga1 = new java.awt.TextField();
        harga2 = new java.awt.TextField();
        harga3 = new java.awt.TextField();
        harga4 = new java.awt.TextField();
        Diskon = new java.awt.TextField();
        Proses = new java.awt.Button();
        Hapus = new java.awt.Button();
        Exit = new java.awt.Button();
        TA = new java.awt.TextArea();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText("Pembayaran");
        getContentPane().add(label1);
        label1.setBounds(160, 20, 80, 20);

        harga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga1ActionPerformed(evt);
            }
        });
        getContentPane().add(harga1);
        harga1.setBounds(170, 60, 120, 20);

        harga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga2ActionPerformed(evt);
            }
        });
        getContentPane().add(harga2);
        harga2.setBounds(170, 90, 120, 20);

        harga3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga3ActionPerformed(evt);
            }
        });
        getContentPane().add(harga3);
        harga3.setBounds(170, 120, 120, 20);

        harga4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga4ActionPerformed(evt);
            }
        });
        getContentPane().add(harga4);
        harga4.setBounds(170, 150, 120, 20);
        getContentPane().add(Diskon);
        Diskon.setBounds(170, 180, 120, 20);

        Proses.setLabel("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(100, 210, 57, 24);

        Hapus.setLabel("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus);
        Hapus.setBounds(190, 210, 57, 24);

        Exit.setLabel("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit);
        Exit.setBounds(280, 210, 57, 24);
        getContentPane().add(TA);
        TA.setBounds(10, 240, 380, 160);

        label2.setText("Diskon");
        getContentPane().add(label2);
        label2.setBounds(120, 180, 40, 20);

        label3.setText("Harga Barang 1");
        getContentPane().add(label3);
        label3.setBounds(70, 60, 100, 20);

        label4.setText("Harga Barang 2");
        getContentPane().add(label4);
        label4.setBounds(70, 90, 100, 20);

        label5.setText("Harga Barang 3");
        getContentPane().add(label5);
        label5.setBounds(70, 120, 100, 20);

        label6.setText("Harga Barang 4");
        getContentPane().add(label6);
        label6.setBounds(70, 150, 100, 20);

        setBounds(0, 0, 416, 444);
    }// </editor-fold>//GEN-END:initComponents

    private void harga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga1ActionPerformed

    private void harga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga2ActionPerformed

    private void harga3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga3ActionPerformed

    private void harga4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga4ActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        int har1 = Integer.parseInt(harga1.getText());
        int har2 = Integer.parseInt(harga2.getText());
        int har3 = Integer.parseInt(harga3.getText());
        int har4 = Integer.parseInt(harga4.getText());
        int diskon = Integer.parseInt(Diskon.getText());
        int total;
        double dis;
        total = har1 + har2 + har3 +har4;  
        dis = diskon  * total / 100;
        double jumlah = total - dis;
        
        TA.setText("Harga Barang  1    :"+har1+"\nHarga Barang  2    :"+har2+"\nHarga Barang  3    :"+har3+"\nHarga Barang  4    :"+har4+"\nDiskon Anda           :"+diskon+"\nTotal Harga             :"+total+"\nJumlah Bayar         :"+jumlah);
                      
    }//GEN-LAST:event_ProsesActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        TA.setText("");
        harga1.setText(" ");
        harga2.setText(" ");
        harga3.setText(" ");
        harga4.setText(" ");
        Diskon.setText(" ");
    }//GEN-LAST:event_HapusActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Diskon;
    private java.awt.Button Exit;
    private java.awt.Button Hapus;
    private java.awt.Button Proses;
    private java.awt.TextArea TA;
    private java.awt.TextField harga1;
    private java.awt.TextField harga2;
    private java.awt.TextField harga3;
    private java.awt.TextField harga4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    // End of variables declaration//GEN-END:variables
}
